const EXACT_NAME_ARABIC: Record<string, string> = {
  "Abstract pinwheel": "دوامة تجريدية",
  Arch: "قوس",
  "Asterisk star": "نجمة على شكل علامة نجمة",
  "Bent arrow": "سهم منحني",
  "Bent down arrow": "سهم منحني لأسفل",
  "Bent left arrow": "سهم منحني لليسار",
  "Bent up arrow": "سهم منحني لأعلى",
  "Blob cloud": "سحابة عضوية",
  "Block arrow": "سهم كتلة",
  "Block down arrow": "سهم كتلة لأسفل",
  "Block left arrow": "سهم كتلة لليسار",
  "Block up arrow": "سهم كتلة لأعلى",
  "Blocky star": "نجمة كتلية",
  "Bold line": "خط عريض",
  "Bookmark banner": "لافتة إشارة مرجعية",
  "Bottom notch bubble": "فقاعة بلسان سفلي",
  "Bulb drop": "قطرة على شكل لمبة",
  "Burst block star": "نجمة انفجارية كتلية",
  "Burst star": "نجمة انفجارية",
  Card: "بطاقة",
  "Centered dot line": "خط بنقطة مركزية",
  "Chamfer block": "شكل بزوايا مشطوفة",
  "Chevron arrow": "سهم شيفرون",
  Circle: "دائرة",
  "Circle endpoints": "خط بنهايات دائرية",
  "Classic drop": "قطرة كلاسيكية",
  "Classic heart": "قلب كلاسيكي",
  "Cloud bubble": "فقاعة سحابية",
  Clover: "برسيم",
  "Compact cloud": "سحابة مدمجة",
  "Cross star": "نجمة متقاطعة",
  "Curved arrow": "سهم منحني",
  "Curved left arrow": "سهم منحني لليسار",
  "Cut bookmark": "إشارة مرجعية مقصوصة",
  "Cutout ring": "حلقة مفرغة",
  Daisy: "زهرة أقحوان",
  "Dash dot line": "خط شرطة ونقطة",
  "Dashed line": "خط متقطع",
  Database: "قاعدة بيانات",
  Decagon: "عشاري الأضلاع",
  Decision: "قرار",
  Delay: "تأخير",
  Diamond: "ماسة",
  "Diamond divider": "فاصل ماسي",
  "Diamond endpoints": "خط بنهايات ماسية",
  "Diamond sparkle": "بريق ماسي",
  Document: "مستند",
  Dodecagon: "اثنا عشري الأضلاع",
  "Dotted line": "خط منقط",
  "Double arrow": "سهم مزدوج",
  "Double diamond": "ماستان",
  "Double line": "خط مزدوج",
  "Double line arrow": "سهم بخطين",
  "Down arrow": "سهم لأسفل",
  "Down chevron arrow": "سهم شيفرون لأسفل",
  "Eight block star": "نجمة كتلية بثماني زوايا",
  "Eight-point star": "نجمة ثمانية",
  "Eleven-point star": "نجمة إحدى عشرية",
  "Fan star": "نجمة مروحية",
  "Five-petal flower": "زهرة بخمس بتلات",
  "Five-point star": "نجمة خماسية",
  "Flat cloud": "سحابة مسطحة",
  "Flat hexagon": "سداسي مسطح",
  "Fluffy cloud": "سحابة منتفخة",
  "Four-point star": "نجمة رباعية",
  "Gear eight": "ترس بثماني أسنان",
  "Gear twelve": "ترس باثنتي عشرة سنة",
  Gearbox: "ترس صندوقي",
  "Half pill": "كبسولة نصفية",
  Heart: "قلب",
  "Heavy cloud": "سحابة كثيفة",
  Heptagon: "سباعي الأضلاع",
  Hexadecagon: "سداسي عشري الأضلاع",
  Hexagon: "سداسي الأضلاع",
  "Indented heart": "قلب مجوف الجانبين",
  "Input output": "إدخال وإخراج",
  "Inverted triangle": "مثلث مقلوب",
  "Layered cloud": "سحابة متعددة الطبقات",
  "Leaning star": "نجمة مائلة",
  "Left arrow": "سهم لليسار",
  "Left chevron arrow": "سهم شيفرون لليسار",
  "Left line arrow": "سهم خطي لليسار",
  "Line arrow": "سهم خطي",
  "Long dashed line": "خط طويل متقطع",
  "Long drop": "قطرة طويلة",
  "Loop cutout": "حلقة مفرغة",
  "Lotus flower": "زهرة لوتس",
  "Nine-point star": "نجمة تساعية",
  Nonagon: "تساعي الأضلاع",
  "Notch banner": "لافتة بفتحة",
  Octagon: "ثماني الأضلاع",
  "Off-page connector": "موصل خارج الصفحة",
  "Oval bubble": "فقاعة بيضاوية",
  Parallelogram: "متوازي الأضلاع",
  "Pear drop": "قطرة كمثرية",
  Pentadecagon: "خماسي عشري الأضلاع",
  Pentagon: "خماسي الأضلاع",
  "Petal block star": "نجمة بتلات كتلية",
  "Petal heart": "قلب بتلات",
  "Petal star": "نجمة بتلات",
  "Picture frame": "إطار صورة",
  Pill: "كبسولة",
  "Pill bubble": "فقاعة كبسولية",
  "Pin drop": "قطرة دبوس",
  "Pinwheel flower": "زهرة دوارة",
  "Pointed banner": "لافتة مدببة",
  "Pointy heart": "قلب مدبب",
  Preparation: "تهيئة",
  Process: "عملية",
  "Quarter circle": "ربع دائرة",
  "Ribbon label": "شريط عنوان",
  "Right arrow": "سهم لليمين",
  "Ring gear": "ترس حلقي",
  "Round bubble left": "فقاعة دائرية لليسار",
  "Round bubble right": "فقاعة دائرية لليمين",
  "Round cloud": "سحابة دائرية",
  "Round cut block": "شكل دائري مقصوص",
  "Round drop": "قطرة دائرية",
  "Round flower": "زهرة دائرية",
  "Round gear": "ترس دائري",
  "Rounded gear": "ترس بحواف دائرية",
  "Rounded heart": "قلب بحواف دائرية",
  "Rounded square": "مربع بحواف دائرية",
  "Rounded wide heart": "قلب عريض بحواف دائرية",
  Semicircle: "نصف دائرة",
  "Seven-point star": "نجمة سباعية",
  "Short drop": "قطرة قصيرة",
  "Shuriken star": "نجمة شوركن",
  "Side notch bubble": "فقاعة بلسان جانبي",
  "Six-petal flower": "زهرة بست بتلات",
  "Six-point star": "نجمة سداسية",
  "Sixteen-point star": "نجمة ست عشرة",
  "Slashed block": "شكل بقطع مائل",
  "Small cloud": "سحابة صغيرة",
  "Soft four-point star": "نجمة رباعية ناعمة",
  "Soft heart": "قلب ناعم",
  "Soft square": "مربع ناعم",
  "Solid line": "خط متصل",
  Sparkle: "بريق",
  "Spiky gear": "ترس مسنن حاد",
  "Spoke star": "نجمة شعاعية",
  Square: "مربع",
  "Square bubble left": "فقاعة مربعة لليسار",
  "Square bubble right": "فقاعة مربعة لليمين",
  "Square divider": "فاصل مربعات",
  "Square endpoints": "خط بنهايات مربعة",
  "Sun gear": "ترس شمسي",
  Sunflower: "دوار الشمس",
  "Swallowtail banner": "لافتة بذيل السنونو",
  "Tag banner": "لافتة علامة",
  "Tall heart": "قلب طويل",
  "Ten-point star": "نجمة عشرية",
  Terminator: "نهاية",
  Tetradecagon: "رباعي عشري الأضلاع",
  "Thick gear": "ترس سميك",
  "Thin drop": "قطرة رفيعة",
  "Thought bubble": "فقاعة تفكير",
  "Ticket ribbon": "شريط تذكرة",
  Trapezoid: "شبه منحرف",
  Triangle: "مثلث",
  Tridecagon: "ثلاثي عشري الأضلاع",
  "Triple line": "خط ثلاثي",
  "Twelve-point star": "نجمة اثنا عشرية",
  "Twin sparkle": "بريق مزدوج",
  "Twist pinwheel": "دوامة ملتوية",
  "U-turn arrow": "سهم انعطاف U",
  Undecagon: "أحد عشري الأضلاع",
  "Up arrow": "سهم لأعلى",
  "Up chevron arrow": "سهم شيفرون لأعلى",
  "Wide cloud": "سحابة عريضة",
  "Wide drop": "قطرة عريضة",
  "Wide heart": "قلب عريض",
  "Wide notch banner": "لافتة عريضة بفتحة",
};

const TOKEN_ARABIC: Record<string, string> = {
  abstract: "تجريدي",
  arch: "قوس",
  arrow: "سهم",
  asterisk: "نجمي",
  badge: "شارة",
  banner: "لافتة",
  basic: "أساسي",
  bent: "منحني",
  blob: "عضوي",
  block: "كتلة",
  blocky: "كتلي",
  bold: "عريض",
  bookmark: "إشارة مرجعية",
  border: "إطار",
  bottom: "سفلي",
  box: "صندوق",
  bubble: "فقاعة",
  bulb: "لمبة",
  burst: "انفجاري",
  capsule: "كبسولة",
  card: "بطاقة",
  centered: "مركزي",
  chamfer: "مشطوف",
  chevron: "شيفرون",
  circle: "دائرة",
  classic: "كلاسيكي",
  cloud: "سحابة",
  clover: "برسيم",
  cog: "ترس",
  compact: "مدمج",
  connector: "موصل",
  corner: "زاوية",
  cross: "متقاطع",
  curve: "منحنى",
  curved: "منحني",
  cut: "مقصوص",
  cutout: "مفرغ",
  cylinder: "أسطوانة",
  d: "شكل D",
  door: "باب",
  daisy: "أقحوان",
  dash: "شرطة",
  dashed: "متقطع",
  database: "قاعدة بيانات",
  decagon: "عشاري الأضلاع",
  decision: "قرار",
  delay: "تأخير",
  diamond: "ماسي",
  divider: "فاصل",
  document: "مستند",
  dodecagon: "اثنا عشري الأضلاع",
  dot: "نقطة",
  dotted: "منقط",
  double: "مزدوج",
  down: "لأسفل",
  direction: "اتجاه",
  eight: "ثماني",
  eleven: "إحدى عشرية",
  endpoints: "نهايات",
  fan: "مروحي",
  filled: "ممتلئ",
  five: "خماسية",
  flag: "راية",
  flower: "زهرة",
  flat: "مسطح",
  fluffy: "منتفخة",
  flowchart: "مخطط تدفق",
  four: "رباعية",
  frame: "إطار",
  gear: "ترس",
  gearbox: "صندوقي",
  half: "نصف",
  heart: "قلب",
  heavy: "كثيفة",
  heptagon: "سباعي الأضلاع",
  hexadecagon: "سداسي عشري الأضلاع",
  hexagon: "سداسي الأضلاع",
  indented: "مجوف",
  input: "إدخال",
  inverted: "مقلوب",
  label: "عنوان",
  layered: "متعدد الطبقات",
  leaning: "مائل",
  left: "لليسار",
  line: "خط",
  long: "طويل",
  manual: "يدوي",
  marker: "علامة",
  lotus: "لوتس",
  loop: "حلقة",
  nine: "تساعية",
  nonagon: "تساعي الأضلاع",
  notch: "فتحة",
  octagon: "ثماني الأضلاع",
  offpage: "خارج الصفحة",
  off: "خارج",
  page: "الصفحة",
  output: "إخراج",
  oval: "بيضاوية",
  parallelogram: "متوازي الأضلاع",
  pear: "كمثرية",
  pentadecagon: "خماسي عشري الأضلاع",
  pentagon: "خماسي الأضلاع",
  petal: "بتلات",
  picture: "صورة",
  pill: "كبسولة",
  pin: "دبوس",
  pinwheel: "دوامة",
  pointed: "مدبب",
  pointy: "مدبب",
  polygon: "مضلع",
  preparation: "تهيئة",
  process: "عملية",
  quarter: "ربع",
  rectangle: "مستطيل",
  rhombus: "معين",
  ribbon: "شريط",
  right: "لليمين",
  ring: "حلقي",
  round: "دائري",
  rounded: "بحواف دائرية",
  semicircle: "نصف دائرة",
  separator: "فاصل",
  seven: "سباعية",
  shape: "شكل",
  short: "قصيرة",
  shuriken: "شوركن",
  side: "جانبي",
  six: "سداسية",
  sixteen: "ست عشرة",
  slashed: "مشقوق",
  slanted: "مائل",
  small: "صغيرة",
  soft: "ناعم",
  solid: "متصل",
  sparkle: "بريق",
  speech: "كلام",
  spike: "شوكي",
  spiky: "حاد",
  spoke: "شعاعي",
  square: "مربع",
  star: "نجمة",
  sun: "شمس",
  sunflower: "دوار الشمس",
  swallowtail: "ذيل السنونو",
  tag: "علامة",
  tall: "طويل",
  teardrop: "قطرة دمعة",
  ten: "عشرية",
  terminator: "نهاية",
  tetradecagon: "رباعي عشري الأضلاع",
  thick: "سميك",
  thirteen: "ثلاثي عشر",
  thin: "رفيعة",
  thought: "تفكير",
  ticket: "تذكرة",
  trapezoid: "شبه منحرف",
  triangle: "مثلث",
  tridecagon: "ثلاثي عشري الأضلاع",
  triple: "ثلاثي",
  twelve: "اثنا عشرية",
  twin: "مزدوج",
  twist: "ملتوية",
  two: "ثنائي",
  turn: "انعطاف",
  uturn: "انعطاف U",
  u: "U",
  undecagon: "أحد عشري الأضلاع",
  up: "لأعلى",
  weather: "طقس",
  wide: "عريض",
};

function normalizeToken(token: string) {
  return String(token || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "");
}

function joinArabicTokens(tokens: string[]) {
  return tokens.filter(Boolean).join(" ").replace(/\s+/g, " ").trim();
}

export function localizeBuiltInShapeName(name: string) {
  const exact = EXACT_NAME_ARABIC[String(name || "")];
  if (exact) return exact;

  const tokens = String(name || "")
    .trim()
    .split(/\s+/)
    .map((token) => TOKEN_ARABIC[normalizeToken(token)] || token);

  return joinArabicTokens(tokens) || String(name || "");
}

export function localizeBuiltInShapeKeywords(keywords: string[]) {
  return Array.from(
    new Set(
      (Array.isArray(keywords) ? keywords : [])
        .map((keyword) => {
          const exact = EXACT_NAME_ARABIC[String(keyword || "")];
          if (exact) return exact;
          return joinArabicTokens(
            String(keyword || "")
              .split(/\s+/)
              .map((token) => TOKEN_ARABIC[normalizeToken(token)] || token)
          );
        })
        .filter(Boolean)
    )
  );
}
